shiny:
  proxy:
    title: Research Institute for Nature and Forest (INBO)
    logo-url: http://data.inbo.be/ipt/logo.do?r=broedvogel-atlas-occurrences
    landing-page: /
    heartbeat-rate: 10000
    heartbeat-timeout: 60000
    port: 8080
    authentication: simple
    admin-groups: scientists
    # Simple auth configuration
    users:
    - name: demo1
      password: demo1
      groups: scientists
    - name: demo2
      password: demo2
      groups: mathematicians
    # LDAP configuration
    ldap:
      url: ldap://ldap.forumsys.com:389/dc=example,dc=com
      user-dn-pattern: uid={0}
      group-search-base:
      group-search-filter: (uniqueMember={0})
      manager-dn: cn=read-only-admin,dc=example,dc=com
      manager-password: password
    # Docker configuration
    docker:
      cert-path: /home/none
      url: http://localhost:2375
      host: 127.0.0.1
      port-range-start: 20000
  apps:
  - name: 02_wog
    display-name: Visualisatie woonuitbreidingsgebieden
    description: Visualisatie van landgebruik en ecosysteemdiensten van de individuele woonuitbreidingsgebieden   
    docker-cmd: ["R", "-e woonuitbreidingsgebieden::run_wog()"]
    docker-image: wog1
    groups: scientists, mathematicians
logging:
  file:
    shinyproxy.log
