version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/woonuitbreidingsgebieden
hooks:
  BeforeInstall:
    - location: scripts/cleanup-woonuitbreidingsgebieden.sh
      timeout: 300
  AfterInstall:
    - location: scripts/woonuitbreidingsgebieden.sh
      timeout: 3600
permissions:
  - object: /home/ubuntu/woonuitbreidingsgebieden
    owner: ubuntu
    group: ubuntu
    mode: 764
