version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/woonuitbreidingsgebieden
hooks:
  AfterInstall:
    - location: scripts/woonuitbreidingsgebieden.sh
      timeout: 1000
permissions:
  - object: /home/ubuntu/woonuitbreidingsgebieden
    owner: ubuntu
    group: ubuntu
    mode: 764