#!/bin/bash
### BEGIN INIT INFO
# Provides:          Start Woonuitbreidingsgebieden
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Spin up R docker image for Woonuitbreidingsgebieden
### END INIT INFO

case $1 in
    start)
        /bin/bash /home/ubuntu/woonuitbreidingsgebieden/scripts/startshiny.sh
    ;;
    stop)
        /bin/bash /home/ubuntu/woonuitbreidingsgebieden/scripts/stopshiny.sh
    ;;
    restart)
        /bin/bash /home/ubuntu/woonuitbreidingsgebieden/scripts/stopshiny.sh
        /bin/bash /home/ubuntu/woonuitbreidingsgebieden/scripts/startshiny.sh
    ;;
esac
exit 0